apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}
  namespace: {{ default .Chart.Name .Values.namespaceOverride }}
  labels:
    app: {{ default .Chart.Name .Values.nameOverride }}

spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ default .Chart.Name .Values.nameOverride }}
      
  template:
    metadata:
      labels:
        app: {{ default .Chart.Name .Values.nameOverride }}
    spec:
      containers:
        - name: {{ default .Chart.Name .Values.nameOverride }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ default "3001" .Values.deployment.port }}
          volumeMounts:
            - name: pvc-{{ default .Chart.Name .Values.nameOverride }}
              mountPath: /app/data

          resources:
            requests:
              memory: "{{ default "256Mi" .Values.deployment.request.memory }}"
              cpu: "{{ default "150m" .Values.deployment.request.cpu }}"

      volumes:
        - name: pvc-{{ default .Chart.Name .Values.nameOverride }}
          persistentVolumeClaim:
            claimName: pvc-{{ default .Chart.Name .Values.nameOverride }}
