{{- if .Values.isEnablePersistVolume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ default .Chart.Name .Values.nameOverride }}

spec:
  capacity:
    storage: {{ .Values.persistVolume.size }}
  volumeMode: {{ .Values.persistVolume.volumemode }}
  accessModes:
    - {{ .Values.persistVolume.accessmode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistVolume.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.persistVolume.storageClass }}
  csi:
    driver: {{ .Values.persistVolume.csi.driver }}
    volumeHandle: {{ .Values.persistVolume.csi.handle }}
{{- end }}