name: prevent-file-change

on:
  pull_request:

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent file change
        uses: xFharGil/prevent-file-change-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Regex, /src/lang/*.json is not allowed to be changed, except for /src/lang/en.json
          pattern: '^(?!src/lang/en\.mark.up$)src/lang/.*\.mark.up$'
          trustedAuthors: MarkdownBot

